# Generated by Django 4.2.7 on 2025-09-28 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='account_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='temp_email',
            field=models.EmailField(blank=True, help_text='Email for registration before user creation', max_length=254),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='temp_user_type',
            field=models.CharField(blank=True, help_text='User type for registration before user creation', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='temp_username',
            field=models.CharField(blank=True, help_text='Username for registration before user creation', max_length=150),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='transaction_desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='transaction_type',
            field=models.CharField(choices=[('REGISTRATION', 'Registration Fee'), ('SUBSCRIPTION', 'Monthly Subscription')], default='SUBSCRIPTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['checkout_request_id'], name='payments_su_checkou_228e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['status', 'transaction_type'], name='payments_su_status_16c149_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['payment_date'], name='payments_su_payment_d70616_idx'),
        ),
    ]
