# Generated by Django 4.2.7 on 2025-09-29 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscriptionpayment_account_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=1.0, help_text='Registration fee in KES (minimum 1.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('subscription_fee', models.DecimalField(decimal_places=2, default=100.0, help_text='Monthly subscription fee in KES (minimum 1.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True, help_text='Only one settings instance can be active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
