# Generated by Django 4.2.7 on 2025-09-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='temp_password',
            field=models.CharField(blank=True, help_text='Hashed password for registration before user creation', max_length=255),
        ),
    ]
