# Generated by Django 4.2.7 on 2025-09-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_subscriptionpayment_temp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='temp_password',
            field=models.CharField(blank=True, help_text='Temporary password for registration before user creation', max_length=128, null=True),
        ),
    ]
