# Generated by Django 4.2.7 on 2025-09-27 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Job title/position', max_length=200)),
                ('description', models.TextField(help_text='Detailed job description')),
                ('requirements', models.TextField(help_text='Required skills and qualifications')),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities (optional)')),
                ('company_name', models.CharField(help_text='Company or startup name', max_length=200)),
                ('company_description', models.TextField(blank=True, help_text='Brief company description')),
                ('location', models.CharField(help_text='Job location', max_length=200)),
                ('remote_ok', models.BooleanField(default=False, help_text='Remote work allowed')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('education', 'Education'), ('real_estate', 'Real Estate'), ('agriculture', 'Agriculture'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('junior', 'Junior (2-4 years)'), ('mid', 'Mid Level (4-7 years)'), ('senior', 'Senior Level (7-10 years)'), ('lead', 'Lead/Principal (10+ years)'), ('executive', 'Executive Level')], max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary (optional)', max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary (optional)', max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='KES', help_text='Currency code (KES, USD, etc.)', max_length=3)),
                ('equity_offered', models.BooleanField(default=False, help_text='Equity/stock options available')),
                ('skills_required', models.TextField(help_text='Required skills (comma-separated)')),
                ('benefits', models.TextField(blank=True, help_text='Benefits and perks offered')),
                ('application_deadline', models.DateTimeField(blank=True, help_text='Application deadline', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured job posting')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField(help_text='Cover letter or application message')),
                ('custom_resume', models.FileField(blank=True, help_text='Upload a custom resume for this application', null=True, upload_to='job_applications/')),
                ('portfolio_links', models.TextField(blank=True, help_text='Additional portfolio links (one per line)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_made', 'Offer Made'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('hired', 'Hired')], default='pending', max_length=20)),
                ('status_notes', models.TextField(blank=True, help_text='Internal notes about status change')),
                ('interview_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('interview_location', models.CharField(blank=True, help_text='Interview location or video link', max_length=200)),
                ('interview_notes', models.TextField(blank=True, help_text='Interview feedback and notes')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(limit_choices_to={'user_type__in': ['regular', 'job_seeker']}, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobposting')),
                ('status_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Name this job alert', max_length=100)),
                ('keywords', models.CharField(blank=True, help_text='Keywords to search for', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Location filter', max_length=100)),
                ('remote_only', models.BooleanField(default=False)),
                ('job_type', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], max_length=20)),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Entry Level (0-2 years)'), ('junior', 'Junior (2-4 years)'), ('mid', 'Mid Level (4-7 years)'), ('senior', 'Senior Level (7-10 years)'), ('lead', 'Lead/Principal (10+ years)'), ('executive', 'Executive Level')], max_length=20)),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('education', 'Education'), ('real_estate', 'Real Estate'), ('agriculture', 'Agriculture'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='daily', max_length=20)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(limit_choices_to={'user_type__in': ['regular', 'job_seeker']}, on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Alert',
                'verbose_name_plural': 'Job Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSavedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this job')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.jobposting')),
                ('user', models.ForeignKey(limit_choices_to={'user_type__in': ['regular', 'job_seeker']}, on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Job',
                'verbose_name_plural': 'Saved Jobs',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'job_posting')},
            },
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['is_active', '-created_at'], name='jobs_jobpos_is_acti_3dea45_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['industry', 'experience_level'], name='jobs_jobpos_industr_f0ff6d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['location', 'remote_ok'], name='jobs_jobpos_locatio_7b0efe_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant', '-applied_at'], name='jobs_jobapp_applica_c5d0c0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job_posting', 'status'], name='jobs_jobapp_job_pos_71ab81_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status', '-applied_at'], name='jobs_jobapp_status_ebd779_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job_posting', 'applicant')},
        ),
    ]
