"""
Django settings for investor_platform project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-$=nzyi-emiel-8y7$ci#^qrz+qsi^sf59a!^+--g8gc@#kk@(r')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,bazuuconnect.com,www.bazuuconnect.com,138.68.170.226').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'accounts.apps.AccountsConfig',
    'pitches',
    'payments',
    'chat',
    'admin_panel',
    'jobs',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'investor_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.unread_messages',
            ],
        },
    },
]

# Database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='investor_platform'),
        'USER': config('DB_USER', default='investor_user'),
        'PASSWORD': config('DB_PASSWORD', default='@Benson100'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    }
}

# More restrictive file types
ALLOWED_CHAT_FILE_TYPES = [
    # Images (common and safe)
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',

    # Documents (read-only formats preferred)
    'application/pdf',

    # Text
    'text/plain',
]


# Add these security settings
SECURE_FILE_UPLOAD_SETTINGS = {
    'MAX_FILE_SIZE': 20 * 1024 * 1024,  # 5MB
    'ALLOWED_EXTENSIONS': ['.jpg', '.jpeg', '.png', '.gif', '.pdf', '.txt'],
    'SCAN_FILES': True,  # Enable if you add virus scanning
    'MAX_FILES_PER_USER_PER_DAY': 50,  # Rate limiting
    'MAX_FILES_PER_MESSAGE': 1,
}

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'  # Updated to Kenya timezone
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles' 

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 10MB

# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# M-Pesa Configuration with Environment Switching
MPESA_ENVIRONMENT = config('MPESA_ENVIRONMENT', default='sandbox')

if MPESA_ENVIRONMENT == 'production':
    # Production M-Pesa Credentials
    MPESA_CONSUMER_KEY = config('MPESA_PROD_CONSUMER_KEY')
    MPESA_CONSUMER_SECRET = config('MPESA_PROD_CONSUMER_SECRET')
    MPESA_SHORTCODE = config('MPESA_PROD_SHORTCODE')
    MPESA_PASSKEY = config('MPESA_PROD_PASSKEY')
    MPESA_API_URL = 'https://api.safaricom.co.ke'
else:
    # Sandbox M-Pesa Credentials
    MPESA_CONSUMER_KEY = config('MPESA_SANDBOX_CONSUMER_KEY')
    MPESA_CONSUMER_SECRET = config('MPESA_SANDBOX_CONSUMER_SECRET')
    MPESA_SHORTCODE = config('MPESA_SANDBOX_SHORTCODE')
    MPESA_PASSKEY = config('MPESA_SANDBOX_PASSKEY')
    MPESA_API_URL = 'https://sandbox.safaricom.co.ke'

# Common M-Pesa settings
MPESA_EXPRESS_SHORTCODE = MPESA_SHORTCODE
MPESA_BUSINESS_SHORTCODE = MPESA_SHORTCODE
MPESA_CALLBACK_URL = config('MPESA_CALLBACK_URL', default='https://bazuuconnect.com/payments/callback/')

# Subscription Settings
SUBSCRIPTION_PRICE = config('SUBSCRIPTION_PRICE', default=500, cast=int)
REGISTRATION_FEE = config('REGISTRATION_FEE', default=500, cast=int)

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@bazuuconnect.com')

# ASGI Application
ASGI_APPLICATION = 'investor_platform.asgi.application'

# Configure channel layers
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [config('REDIS_URL', default='redis://127.0.0.1:6379')],
        },
    },
}

# Development settings
import sys
if DEBUG and 'runserver' in sys.argv:
    import django.utils.autoreload
    django.utils.autoreload.RUN_RELOADER = False

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_REDIRECT_EXEMPT = []
    # SECURE_SSL_REDIRECT = True
    # SESSION_COOKIE_SECURE = True
    # CSRF_COOKIE_SECURE = True




LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.contrib.auth': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}
